import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {validateManifest} from '../frontend/atlas-core.mjs';
import './build-porsche-systems.mjs';
const manifest=JSON.parse(await readFile('src/demo/data/vehicle_atlas.json','utf8'));
const asset=await readFile('src/demo/static/models/porsche-911-carrera-4s.glb');
if(createHash('sha256').update(asset).digest('hex')!==manifest.sha256 || asset.length!==manifest.bytes) throw new Error('Vehicle source hash/size mismatch.');
if(asset.readUInt32LE(0)!==0x46546c67 || asset.readUInt32LE(4)!==2 || asset.readUInt32LE(8)!==asset.length) throw new Error('Invalid GLB container.');
const json=JSON.parse(asset.subarray(20,20+asset.readUInt32LE(12)).toString('utf8'));
validateManifest(manifest,json.meshes.length);
if(!json.asset.extras.author.startsWith(manifest.author) || !json.asset.extras.license.startsWith('CC-BY-SA-4.0')) throw new Error('Asset provenance mismatch.');
await mkdir('src/demo/static/atlas/draco',{recursive:true});
await copyFile('node_modules/three/examples/jsm/libs/draco/draco_decoder.js','src/demo/static/atlas/draco/draco_decoder.js');
await copyFile('node_modules/three/LICENSE','src/demo/static/atlas/THREE-LICENSE.txt');
await build({entryPoints:['frontend/atlas.js'],outfile:'src/demo/static/atlas/atlas.js',bundle:true,minify:true,format:'esm',legalComments:'eof',target:'es2022'});
const triangles=json.meshes.reduce((n,m)=>n+m.primitives.reduce((p,v)=>p+json.accessors[v.indices].count/3,0),0);
await writeFile('src/demo/static/atlas/build.json',JSON.stringify({asset_sha256:manifest.sha256,bytes:asset.length,meshes:json.meshes.length,triangles,components:manifest.components.length,three:'0.186.1'},null,2)+'\n');
console.log(`Worked: ${manifest.components.length} component groups, ${json.meshes.length} meshes, ${triangles} triangles; licensed asset verified and viewer bundled.`);
